export const ADDWORKORDER_REQUEST = "ADDWORKORDER_REQUEST";
export const ADDWORKORDER_SUCCESS = "ADDWORKORDER_SUCCESS";
export const ADDWORKORDER_FAIL = "ADDWORKORDER_FAIL";

export const LOAD_ADDWORKORDER_REQUEST = "LOAD_ADDWORKORDER_REQUEST";
export const LOAD_ADDWORKORDER_SUCCESS = "LOAD_ADDWORKORDER_SUCCESS";
export const LOAD_ADDWORKORDER_FAIL = "LOAD_ADDWORKORDER_FAIL";


export const ALL_ADDWORKORDERS_REQUEST = "ALL_ADDWORKORDERS_REQUEST";
export const ALL_ADDWORKORDERS_SUCCESS = "ALL_ADDWORKORDERS_SUCCESS";
export const ALL_ADDWORKORDERS_FAIL = "ALL_ADDWORKORDERS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";