export const CUSTOMER_REQUEST = "CUSTOMER_REQUEST";
export const CUSTOMER_SUCCESS = "CUSTOMER_SUCCESS";
export const CUSTOMER_FAIL = "CUSTOMER_FAIL";


export const LOAD_CUSTOMER_REQUEST = "LOAD_CUSTOMER_REQUEST";
export const LOAD_CUSTOMER_SUCCESS = "LOAD_CUSTOMER_SUCCESS";
export const LOAD_CUSTOMER_FAIL = "LOAD_CUSTOMER_FAIL";


export const ALL_CUSTOMER_REQUEST = "ALL_CUSTOMER_REQUEST";
export const ALL_CUSTOMER_SUCCESS = "ALL_CUSTOMER_SUCCESS";
export const ALL_CUSTOMER_FAIL = "ALL_CUSTOMER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";